# Generated by Django 4.2 on 2023-04-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em ')),
            ],
        ),
        migrations.CreateModel(
            name='SubTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em ')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(help_text='Digite o seu nome COMPLETO', max_length=255, null=True, unique=True, verbose_name='Nome')),
                ('email', models.EmailField(max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Cria em')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_spent', models.TimeField()),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em ')),
                ('subtask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marker.subtaskmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TimerMarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(auto_now_add=True, verbose_name='Iniciado em ')),
                ('finished_at', models.DateField(auto_now_add=True, verbose_name='Finalizado em')),
                ('time_spent', models.TimeField()),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marker.timermodel')),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Criado em ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marker.companymodel')),
            ],
        ),
        migrations.AddField(
            model_name='subtaskmodel',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marker.taskmodel'),
        ),
    ]
